
# 'PrintMotd'                       => 'yes',
# 'X11Forwarding'                   => 'no',
# 'PrintLastLog'                    => 'yes',
# 'UsePrivilegeSeparation'          => 'sandbox'

- name: Disable DNS using
  replace:
    path: "/etc/ssh/sshd_config"
    regexp: "^#UseDNS yes"
    replace: "UseDNS no"
    backup: no

- name: Add RSAAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'RSAAuthentication yes'
    line: 'RSAAuthentication yes'

- name: PubkeyAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PubkeyAuthentication yes'
    line: 'PubkeyAuthentication yes'

- name: PermitRootLogin
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin no'
    line: 'PermitRootLogin no'

- name: PermitTunnel
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitTunnel no'
    line: 'PermitTunnel no'

- name: ChallengeResponseAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'ChallengeResponseAuthentication no'
    line: 'ChallengeResponseAuthentication no'

- name: DenyUsers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'DenyUsers ec2-user'
    line: 'DenyUsers ec2-user'

- name: PrintMotd
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PrintMotd yes'
    line: 'PrintMotd yes'

- name: X11Forwarding
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'X11Forwarding no'
    line: 'X11Forwarding no'

- name: PrintLastLog
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PrintLastLog yes'
    line: 'PrintLastLog yes'

- name: UsePrivilegeSeparation
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'UsePrivilegeSeparation sandbox'
    line: 'UsePrivilegeSeparation sandbox'    
