---
- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  vars:
    cur_region: "{{ region }}"
    grafana_admin_password: "1111"
  roles:
    - common
    - sshd-config
    - grafana
